import { definePrototypeDataContract, type FieldSpec } from "./data-contract-schema";

function crearCampoFormulario(
  id: string,
  productDescription: string,
  dataType: FieldSpec["dataType"],
  usedIn: string[],
  dataClassification: FieldSpec["dataClassification"] = "internal",
  required = true,
): FieldSpec {
  return {
    id,
    productDescription,
    dataType,
    required,
    usage: {
      visible: true,
      editable: true,
      calculated: false,
      technical: false,
    },
    usedIn,
    origin: "generatedByUsability",
    source: { kind: "unknown" },
    dataClassification,
    technicalValidation: {
      status: "pendingTi",
      note: `TI debe confirmar la fuente y persistencia definitiva de ${id}.`,
    },
  };
}

/**
 * Fuente de verdad de los datos usados por el prototipo.
 *
 * El designer describe el producto en lenguaje natural; el agente mantiene este
 * contrato y ejecuta `pnpm check:data-contract` antes de implementar la UI.
 */
export const prototypeDataContract = definePrototypeDataContract({
  contractVersion: "1",
  project: {
    name: "portal-proteccion-patrimonial",
    description: "Ficha guiada para recopilar antecedentes de gestiones patrimoniales.",
  },
  entities: {
    cliente: {
      id: "cliente",
      productDescription: "Persona que completa sus antecedentes en el portal.",
      roleInExperience:
        "Permite asociar la ayuda del flujo con el Ejecutivo o Ejecutiva Legal asignado al cliente.",
      usedIn: ["Portal completo", "Ayuda global por WhatsApp"],
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: {
        status: "pendingTi",
        note: "TI debe confirmar la fuente definitiva de la asignación del Ejecutivo o Ejecutiva Legal por cliente.",
      },
      fields: {
        ejecutivoLegalNombre: {
          id: "ejecutivoLegalNombre",
          productDescription: "Nombre del Ejecutivo o Ejecutiva Legal asignado al cliente.",
          dataType: "string",
          required: true,
          usage: {
            visible: false,
            editable: false,
            calculated: false,
            technical: true,
          },
          usedIn: ["Configuración de ayuda global por WhatsApp"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe confirmar el atributo de origen para el nombre del Ejecutivo o Ejecutiva Legal asignado.",
          },
        },
        ejecutivoLegalTelefonoWhatsapp: {
          id: "ejecutivoLegalTelefonoWhatsapp",
          productDescription:
            "Teléfono de WhatsApp del Ejecutivo o Ejecutiva Legal asignado al cliente.",
          dataType: "string",
          required: true,
          usage: {
            visible: false,
            editable: false,
            calculated: false,
            technical: true,
          },
          usedIn: ["Enlace global de ayuda por WhatsApp"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe confirmar el atributo de origen y el formato autorizado del teléfono de WhatsApp.",
          },
        },
      },
    },
    sociedad: {
      id: "sociedad",
      productDescription: "Sociedad que el cliente constituirá junto al segundo socio.",
      roleInExperience:
        "Reúne los antecedentes esenciales para redactar la constitución de la sociedad.",
      usedIn: ["Datos de la sociedad", "Constitución de sociedades"],
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: {
        status: "pendingTi",
        note: "TI y el equipo legal deben validar la fuente y persistencia de los datos de la sociedad.",
      },
      fields: {
        nombreSociedad: crearCampoFormulario(
          "nombreSociedad",
          "Nombre que tendrá la sociedad.",
          "string",
          ["Datos de la sociedad", "Redacción de la constitución"],
        ),
        tipoSociedad: {
          id: "tipoSociedad",
          productDescription:
            "Tipo societario que determina la terminación del nombre y la forma de participación.",
          dataType: "enum",
          enumValues: ["eirl", "spa", "sa", "limitada"],
          required: true,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: [
            "Datos de la sociedad",
            "Cantidad de acciones",
            "Participación del segundo socio",
          ],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y el equipo legal deben validar el catálogo definitivo de tipos societarios.",
          },
        },
        actividadSociedad: crearCampoFormulario(
          "actividadSociedad",
          "Descripción en palabras del cliente de la actividad, productos o servicios a los que se dedicará la sociedad.",
          "string",
          ["Datos de la sociedad", "Definición del objeto o giro social"],
        ),
        capitalSociedad: crearCampoFormulario(
          "capitalSociedad",
          "Monto en pesos chilenos con que contará la sociedad para realizar sus actividades y negocios.",
          "number",
          ["Datos de la sociedad", "Redacción de la constitución"],
        ),
        cantidadAcciones: crearCampoFormulario(
          "cantidadAcciones",
          "Cantidad de acciones en que se dividirá el capital de una SpA o S.A.",
          "number",
          ["Participación en SpA o S.A."],
          "internal",
          false,
        ),
        duracionSociedad: crearCampoFormulario(
          "duracionSociedad",
          "Plazo de duración de la sociedad, que puede ser definido o indefinido.",
          "string",
          ["Datos de la sociedad", "Redacción de la constitución"],
        ),
        domicilioSociedad: crearCampoFormulario(
          "domicilioSociedad",
          "Domicilio que tendrá la sociedad.",
          "string",
          ["Datos de la sociedad", "Redacción de la constitución"],
        ),
        administradorSociedad: {
          id: "administradorSociedad",
          productDescription:
            "Indica si el cliente, el segundo socio u otra persona administrará o representará a la sociedad.",
          dataType: "enum",
          enumValues: ["yo", "socio", "otro"],
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Datos de la sociedad", "Administración o representación de la sociedad"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y el equipo legal deben validar la persistencia y el alcance de la administración o representación según el tipo societario.",
          },
        },
      },
    },
    segundoSocio: {
      id: "segundoSocio",
      productDescription: "Persona que constituirá la sociedad junto al cliente.",
      roleInExperience:
        "Reúne sus datos personales estándar y permite comprobar que sea mayor de edad.",
      usedIn: ["Datos del segundo socio", "Constitución de sociedades"],
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "sensitive",
      technicalValidation: {
        status: "pendingTi",
        note: "TI y el equipo legal deben validar la fuente y persistencia de los datos del segundo socio.",
      },
      fields: {
        nombres: crearCampoFormulario(
          "nombres",
          "Nombres del segundo socio.",
          "string",
          ["Datos del segundo socio"],
          "sensitive",
        ),
        apellidoPaterno: crearCampoFormulario(
          "apellidoPaterno",
          "Apellido paterno del segundo socio.",
          "string",
          ["Datos del segundo socio"],
          "sensitive",
        ),
        apellidoMaterno: crearCampoFormulario(
          "apellidoMaterno",
          "Apellido materno del segundo socio.",
          "string",
          ["Datos del segundo socio"],
          "sensitive",
        ),
        rut: crearCampoFormulario(
          "rut",
          "RUT del segundo socio.",
          "identifier",
          ["Datos del segundo socio"],
          "sensitive",
        ),
        email: crearCampoFormulario(
          "email",
          "Correo electrónico del segundo socio.",
          "string",
          ["Datos del segundo socio"],
          "sensitive",
        ),
        fechaNacimiento: crearCampoFormulario(
          "fechaNacimiento",
          "Fecha de nacimiento usada para comprobar que el segundo socio tenga 18 años o más.",
          "date",
          ["Datos del segundo socio", "Validación de mayoría de edad"],
          "sensitive",
        ),
        nacionalidad: crearCampoFormulario(
          "nacionalidad",
          "Nacionalidad del segundo socio.",
          "string",
          ["Datos del segundo socio"],
          "sensitive",
        ),
        profesion: crearCampoFormulario(
          "profesion",
          "Profesión u oficio del segundo socio.",
          "string",
          ["Datos del segundo socio"],
          "sensitive",
        ),
        estadoCivil: crearCampoFormulario(
          "estadoCivil",
          "Estado civil del segundo socio.",
          "string",
          ["Datos del segundo socio"],
          "sensitive",
        ),
        regimenMatrimonial: crearCampoFormulario(
          "regimenMatrimonial",
          "Régimen patrimonial del segundo socio cuando corresponde.",
          "string",
          ["Datos del segundo socio"],
          "sensitive",
        ),
        domicilio: crearCampoFormulario(
          "domicilio",
          "Domicilio particular del segundo socio.",
          "string",
          ["Datos del segundo socio"],
          "sensitive",
        ),
        comuna: crearCampoFormulario(
          "comuna",
          "Comuna del domicilio del segundo socio.",
          "string",
          ["Datos del segundo socio"],
          "sensitive",
        ),
        region: crearCampoFormulario(
          "region",
          "Región del domicilio del segundo socio.",
          "string",
          ["Datos del segundo socio"],
          "sensitive",
        ),
        cantidadAccionesSocio: crearCampoFormulario(
          "cantidadAccionesSocio",
          "Cantidad de acciones asignadas al segundo socio en una SpA o S.A.",
          "number",
          ["Participación del segundo socio en SpA o S.A."],
          "sensitive",
          false,
        ),
        porcentajeDerechosSociales: crearCampoFormulario(
          "porcentajeDerechosSociales",
          "Porcentaje de derechos sociales asignado al segundo socio en una sociedad de responsabilidad limitada.",
          "number",
          ["Participación del segundo socio en sociedad Limitada"],
          "sensitive",
          false,
        ),
        esMayorEdad: {
          id: "esMayorEdad",
          productDescription: "Indica si el segundo socio tiene 18 años o más.",
          dataType: "boolean",
          derivation:
            "Se calcula desde fechaNacimiento considerando la fecha actual; es verdadero desde el día en que cumple 18 años.",
          required: true,
          usage: {
            visible: true,
            editable: false,
            calculated: true,
            technical: false,
          },
          usedIn: ["Validación de mayoría de edad", "Continuidad del formulario"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y el equipo legal deben validar la regla definitiva de mayoría de edad.",
          },
        },
      },
      states: [
        {
          id: "menorDeEdad",
          productDescription: "El segundo socio todavía no cumple 18 años.",
          activationCondition: "La edad calculada desde fechaNacimiento es menor a 18 años.",
          visualImpact:
            "Muestra una explicación junto a la fecha de nacimiento e impide continuar.",
          usedIn: ["Datos del segundo socio"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "El equipo legal debe validar el alcance del bloqueo por minoría de edad.",
          },
        },
      ],
    },
    administradorSociedadPersona: {
      id: "administradorSociedadPersona",
      productDescription:
        "Persona distinta del cliente y del segundo socio que administrará o representará a la sociedad.",
      roleInExperience:
        "Reúne los datos personales necesarios cuando el cliente elige a otra persona para administrar o representar.",
      usedIn: ["Datos del administrador", "Datos del representante", "Constitución de sociedades"],
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "sensitive",
      technicalValidation: {
        status: "pendingTi",
        note: "TI y el equipo legal deben validar la fuente, persistencia y uso jurídico de los datos del administrador o representante.",
      },
      fields: {
        nombres: crearCampoFormulario(
          "nombres",
          "Nombres del administrador o representante.",
          "string",
          ["Datos del administrador o representante"],
          "sensitive",
        ),
        apellidoPaterno: crearCampoFormulario(
          "apellidoPaterno",
          "Apellido paterno del administrador o representante.",
          "string",
          ["Datos del administrador o representante"],
          "sensitive",
        ),
        apellidoMaterno: crearCampoFormulario(
          "apellidoMaterno",
          "Apellido materno del administrador o representante.",
          "string",
          ["Datos del administrador o representante"],
          "sensitive",
        ),
        rut: crearCampoFormulario(
          "rut",
          "RUT del administrador o representante.",
          "identifier",
          ["Datos del administrador o representante"],
          "sensitive",
        ),
        email: crearCampoFormulario(
          "email",
          "Correo electrónico del administrador o representante.",
          "string",
          ["Datos del administrador o representante"],
          "sensitive",
        ),
        fechaNacimiento: crearCampoFormulario(
          "fechaNacimiento",
          "Fecha de nacimiento usada para comprobar que el administrador o representante tenga 18 años o más.",
          "date",
          ["Datos del administrador o representante", "Validación de mayoría de edad"],
          "sensitive",
        ),
        nacionalidad: crearCampoFormulario(
          "nacionalidad",
          "Nacionalidad del administrador o representante.",
          "string",
          ["Datos del administrador o representante"],
          "sensitive",
        ),
        profesion: crearCampoFormulario(
          "profesion",
          "Profesión u oficio del administrador o representante.",
          "string",
          ["Datos del administrador o representante"],
          "sensitive",
        ),
        estadoCivil: crearCampoFormulario(
          "estadoCivil",
          "Estado civil del administrador o representante.",
          "string",
          ["Datos del administrador o representante"],
          "sensitive",
        ),
        regimenMatrimonial: crearCampoFormulario(
          "regimenMatrimonial",
          "Régimen patrimonial del administrador o representante cuando corresponde.",
          "string",
          ["Datos del administrador o representante"],
          "sensitive",
        ),
        domicilio: crearCampoFormulario(
          "domicilio",
          "Domicilio particular del administrador o representante.",
          "string",
          ["Datos del administrador o representante"],
          "sensitive",
        ),
        comuna: crearCampoFormulario(
          "comuna",
          "Comuna del domicilio del administrador o representante.",
          "string",
          ["Datos del administrador o representante"],
          "sensitive",
        ),
        region: crearCampoFormulario(
          "region",
          "Región del domicilio del administrador o representante.",
          "string",
          ["Datos del administrador o representante"],
          "sensitive",
        ),
        esMayorEdad: {
          id: "esMayorEdad",
          productDescription: "Indica si el administrador o representante tiene 18 años o más.",
          dataType: "boolean",
          derivation:
            "Se calcula desde fechaNacimiento considerando la fecha actual; es verdadero desde el día en que cumple 18 años.",
          required: true,
          usage: {
            visible: true,
            editable: false,
            calculated: true,
            technical: false,
          },
          usedIn: ["Validación de mayoría de edad", "Continuidad del formulario"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y el equipo legal deben validar la regla definitiva de mayoría de edad para el administrador o representante.",
          },
        },
      },
      states: [
        {
          id: "menorDeEdad",
          productDescription: "El administrador o representante todavía no cumple 18 años.",
          activationCondition: "La edad calculada desde fechaNacimiento es menor a 18 años.",
          visualImpact:
            "Muestra una explicación junto a la fecha de nacimiento e impide continuar.",
          usedIn: ["Datos del administrador o representante"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "El equipo legal debe validar el alcance del bloqueo por minoría de edad.",
          },
        },
      ],
    },
    otorganteMandato: {
      id: "otorganteMandato",
      productDescription:
        "Persona distinta del cliente que otorga poder a un apoderado para firmar en su nombre.",
      roleInExperience:
        "Permite preparar un mandato simple cuando quien necesita representación es el tercero del contrato principal.",
      usedIn: ["Mandato", "Datos de quien otorga el poder"],
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "sensitive",
      technicalValidation: {
        status: "pendingTi",
        note: "TI y el equipo legal deben validar la fuente y persistencia de los datos del tercero otorgante.",
      },
      fields: {
        nombres: crearCampoFormulario(
          "nombres",
          "Nombres de quien otorga el poder.",
          "string",
          ["Datos de quien otorga el poder"],
          "sensitive",
        ),
        apellidoPaterno: crearCampoFormulario(
          "apellidoPaterno",
          "Apellido paterno de quien otorga el poder.",
          "string",
          ["Datos de quien otorga el poder"],
          "sensitive",
        ),
        apellidoMaterno: crearCampoFormulario(
          "apellidoMaterno",
          "Apellido materno de quien otorga el poder.",
          "string",
          ["Datos de quien otorga el poder"],
          "sensitive",
        ),
        rut: crearCampoFormulario(
          "rut",
          "RUT de quien otorga el poder.",
          "identifier",
          ["Datos de quien otorga el poder"],
          "sensitive",
        ),
        email: crearCampoFormulario(
          "email",
          "Correo electrónico de quien otorga el poder.",
          "string",
          ["Datos de quien otorga el poder"],
          "sensitive",
        ),
        fechaNacimiento: crearCampoFormulario(
          "fechaNacimiento",
          "Fecha de nacimiento de quien otorga el poder.",
          "date",
          ["Datos de quien otorga el poder"],
          "sensitive",
        ),
        nacionalidad: crearCampoFormulario(
          "nacionalidad",
          "Nacionalidad de quien otorga el poder.",
          "string",
          ["Datos de quien otorga el poder"],
          "sensitive",
        ),
        profesion: crearCampoFormulario(
          "profesion",
          "Profesión u oficio de quien otorga el poder.",
          "string",
          ["Datos de quien otorga el poder"],
          "sensitive",
        ),
        estadoCivil: crearCampoFormulario(
          "estadoCivil",
          "Estado civil de quien otorga el poder.",
          "string",
          ["Datos de quien otorga el poder"],
          "sensitive",
        ),
        regimenMatrimonial: crearCampoFormulario(
          "regimenMatrimonial",
          "Régimen patrimonial de quien otorga el poder cuando corresponde.",
          "string",
          ["Datos de quien otorga el poder"],
          "sensitive",
        ),
        domicilio: crearCampoFormulario(
          "domicilio",
          "Domicilio de quien otorga el poder.",
          "string",
          ["Datos de quien otorga el poder"],
          "sensitive",
        ),
        comuna: crearCampoFormulario(
          "comuna",
          "Comuna de quien otorga el poder.",
          "string",
          ["Datos de quien otorga el poder"],
          "sensitive",
        ),
        region: crearCampoFormulario(
          "region",
          "Región de quien otorga el poder.",
          "string",
          ["Datos de quien otorga el poder"],
          "sensitive",
        ),
      },
    },
    terceroConfianza: {
      id: "terceroConfianza",
      productDescription:
        "Persona relacionada con la gestión como receptor de una transferencia, apoderado o contraparte.",
      roleInExperience:
        "Permite identificar su rol, evaluar las transferencias y preparar la representación en los mandatos.",
      usedIn: [
        "Datos del tercero de confianza",
        "Evaluación de la transferencia",
        "Persona apoderada",
        "Mandato con autocontrato",
      ],
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "sensitive",
      technicalValidation: {
        status: "pendingTi",
        note: "TI y el equipo legal deben validar la fuente, persistencia y reglas definitivas de evaluación del tercero.",
      },
      fields: {
        otorganteMandato: {
          id: "otorganteMandato",
          productDescription:
            "Indica si el poder del mandato simple lo otorga el cliente o el tercero del contrato principal.",
          dataType: "enum",
          enumValues: ["cliente", "tercero"],
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Mandato", "Selección de quien otorga el poder"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y el equipo legal deben validar la persistencia y efectos jurídicos de la selección.",
          },
        },
        sentidoAutocontrato: {
          id: "sentidoAutocontrato",
          productDescription:
            "Indica si el cliente firma también por el tercero o si el tercero firma también por el cliente.",
          dataType: "enum",
          enumValues: ["clientePorTercero", "terceroPorCliente"],
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Mandato con autocontrato", "Dirección de la representación"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y el equipo legal deben validar la persistencia y efectos jurídicos de la selección.",
          },
        },
        apoderadoCoincideCompareciente: {
          id: "apoderadoCoincideCompareciente",
          productDescription:
            "Indica si la persona apoderada de un mandato general tiene el mismo RUT que la persona contratante o la otra parte del contrato.",
          dataType: "boolean",
          derivation:
            "Compara el RUT normalizado de la persona apoderada con los RUT de ambas partes del contrato.",
          required: false,
          usage: {
            visible: true,
            editable: false,
            calculated: true,
            technical: false,
          },
          usedIn: ["Mandato", "Validación de la persona apoderada"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y el equipo legal deben validar que la coincidencia de RUT impida continuar con el mandato general.",
          },
        },
        fechaNacimiento: {
          id: "fechaNacimiento",
          productDescription: "Fecha de nacimiento usada para calcular la edad del tercero.",
          dataType: "date",
          required: true,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Datos personales del tercero", "Señal de edad menor a 21 años"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe confirmar la fuente y el formato de la fecha de nacimiento del tercero.",
          },
        },
        relacionCliente: {
          id: "relacionCliente",
          productDescription: "Relación del tercero con el cliente.",
          dataType: "enum",
          enumValues: ["hijo", "padreMadre", "hermano", "amigo", "pareja", "socio", "otro"],
          required: true,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Evaluación de parentesco", "Bloqueo de transferencia a cónyuge"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "El equipo legal y TI deben validar el catálogo de relaciones y la exclusión absoluta del cónyuge.",
          },
        },
        reglaTerceroCesionHereditaria: {
          id: "reglaTerceroCesionHereditaria",
          productDescription:
            "Regla que determina si la cesión de derechos hereditarios admite solo a otra persona heredera o también a una persona externa a la herencia.",
          dataType: "enum",
          enumValues: ["soloComunero", "ambos"],
          derivation:
            "Se deriva de la comuna de cada inmueble heredado. Si al menos una comuna pertenece a la jurisdicción de San Miguel o Villa Alemana, exige otra persona heredera; en cualquier otra comuna acepta ambas alternativas.",
          required: false,
          usage: {
            visible: true,
            editable: false,
            calculated: true,
            technical: false,
          },
          usedIn: [
            "Cesión de derechos hereditarios",
            "Orientación para elegir al tercero de confianza",
          ],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y el equipo legal deben validar la matriz de comunas, su mantención y la regla general aplicable a comunas sin una excepción registrada.",
          },
        },
        vinculoComunidadHereditaria: {
          id: "vinculoComunidadHereditaria",
          productDescription:
            "Indica si el tercero elegido es una de las personas herederas o una persona externa a la herencia.",
          dataType: "enum",
          enumValues: ["comunero", "terceroAjeno"],
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Cesión de derechos hereditarios", "Validación del tercero de confianza"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe confirmar dónde se persistirá esta selección y el equipo legal debe validar que sea obligatoria antes de continuar.",
          },
        },
        plenamenteCapaz: {
          id: "plenamenteCapaz",
          productDescription:
            "Indica si un tercero mayor de 60 años se encuentra en plenas facultades mentales.",
          dataType: "boolean",
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Evaluación de facultades mentales", "Solicitud de certificado médico"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "El equipo legal y TI deben validar la redacción de la pregunta, el umbral de edad y la forma de acreditar las facultades mentales.",
          },
        },
        requiereCertificadoFacultadesMentales: {
          id: "requiereCertificadoFacultadesMentales",
          productDescription:
            "Indica si debe solicitarse un certificado médico que acredite las facultades mentales del tercero.",
          dataType: "boolean",
          derivation:
            "Es verdadero cuando el tercero tiene más de 60 años, independientemente de la respuesta sobre sus facultades mentales.",
          required: true,
          usage: {
            visible: true,
            editable: false,
            calculated: true,
            technical: false,
          },
          usedIn: ["Evaluación de la transferencia", "Documentos de la gestión"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "El equipo legal y TI deben validar que la notaría solicite el certificado, que sea emitido por psiquiatra o neurólogo y su requisito documental definitivo.",
          },
        },
        ingresosEstables: {
          id: "ingresosEstables",
          productDescription:
            "Indica si el tercero puede acreditar ingresos estables para respaldar la transferencia ante una eventual revisión del SII.",
          dataType: "boolean",
          required: true,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Señal de riesgo por ingresos"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "El equipo legal y TI deben validar la definición operativa de ingresos acreditables y el alcance de una eventual revisión del SII.",
          },
        },
        requiereConyugeAutorizante: {
          id: "requiereConyugeAutorizante",
          productDescription:
            "Indica si el cónyuge o conviviente civil del tercero debe comparecer a autorizar una transferencia de inmueble.",
          dataType: "boolean",
          derivation:
            "Es verdadero en transferencias de inmuebles cuando el tercero está casado bajo sociedad conyugal o tiene un Acuerdo de Unión Civil bajo comunidad de bienes.",
          required: true,
          usage: {
            visible: true,
            editable: false,
            calculated: true,
            technical: false,
          },
          usedIn: ["Datos del tercero de confianza", "Comparecencia para autorización"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "El equipo legal y TI deben validar los contratos, estados civiles y regímenes que exigen la comparecencia para autorizar.",
          },
        },
        cantidadSenalesRiesgo: {
          id: "cantidadSenalesRiesgo",
          productDescription: "Cantidad de señales de riesgo detectadas para la transferencia.",
          dataType: "number",
          derivation:
            "Suma una señal por edad menor a 21 años, parentesco directo y ausencia de ingresos estables; el resultado va de 0 a 3.",
          required: true,
          usage: {
            visible: true,
            editable: false,
            calculated: true,
            technical: false,
          },
          usedIn: ["Resultado de la evaluación", "Aceptación de riesgos"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "El equipo legal y TI deben validar los factores, ponderación y umbrales de riesgo.",
          },
        },
        transferenciaPermitida: {
          id: "transferenciaPermitida",
          productDescription:
            "Indica si el tercero cumple las condiciones mínimas para transferir.",
          dataType: "boolean",
          derivation:
            "Es falsa cuando el tercero es cónyuge o, siendo mayor de 60 años, responde que no se encuentra en plenas facultades mentales.",
          required: true,
          usage: {
            visible: true,
            editable: false,
            calculated: true,
            technical: false,
          },
          usedIn: ["Bloqueo de Guardar y continuar"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "El equipo legal y TI deben validar los impedimentos absolutos para la transferencia.",
          },
        },
        cantidadEscriturasInmobiliariasAsignadas: {
          id: "cantidadEscriturasInmobiliariasAsignadas",
          productDescription:
            "Cantidad de escrituras inmobiliarias incluidas en las que esta persona ya fue elegida como tercero de confianza.",
          dataType: "number",
          derivation:
            "Cuenta por RUT las gestiones principales de aporte inmobiliario SRL, compraventa de inmueble, compraventa de inmueble y usufructo, cesión de derechos, compraventa de nuda propiedad y cesión de derechos hereditarios. Excluye la gestión actual, mandatos, liquidación de sociedad conyugal y bienes individuales dentro de una misma escritura.",
          required: false,
          usage: {
            visible: true,
            editable: false,
            calculated: true,
            technical: false,
          },
          usedIn: ["Validación del RUT del tercero de confianza"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe validar la consulta transversal por cliente, los estados de gestión que participan y la aplicación concurrente del máximo de dos escrituras.",
          },
        },
        estadoLimiteEscriturasInmobiliarias: {
          id: "estadoLimiteEscriturasInmobiliarias",
          productDescription:
            "Estado que informa si el tercero está disponible, corresponde a su segundo uso o ya alcanzó el máximo permitido.",
          dataType: "enum",
          enumValues: ["disponible", "segundoUso", "limiteAlcanzado"],
          derivation:
            "Disponible con cero usos previos, segundoUso con uno y limiteAlcanzado con dos o más.",
          required: false,
          usage: {
            visible: true,
            editable: false,
            calculated: true,
            technical: false,
          },
          usedIn: ["Ayuda y bloqueo junto al RUT del tercero de confianza"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y el equipo legal deben confirmar la fuente definitiva y aplicar esta invariante también en backend.",
          },
        },
        aceptaRiesgosTransferencia: {
          id: "aceptaRiesgosTransferencia",
          productDescription:
            "Registra que el cliente entiende y acepta los riesgos tributarios y legales informados, y decide continuar con esa persona.",
          dataType: "boolean",
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Continuidad con tercero riesgoso"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y el equipo legal deben validar el texto, evidencia y persistencia de la aceptación de riesgos.",
          },
        },
        regionesDomicilioDistintas: {
          id: "regionesDomicilioDistintas",
          productDescription:
            "Indica si el cliente y el tercero de confianza tienen domicilio en regiones distintas.",
          dataType: "boolean",
          derivation:
            "Compara la región del domicilio del cliente con la región del domicilio del tercero, normalizando mayúsculas y tildes.",
          required: false,
          usage: {
            visible: true,
            editable: false,
            calculated: true,
            technical: false,
          },
          usedIn: ["Disponibilidad para firma conjunta", "Selección de mandato"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe validar la fuente definitiva de ambas regiones y el criterio de comparación.",
          },
        },
        disponibilidadFirmaConjunta: {
          id: "disponibilidadFirmaConjunta",
          productDescription:
            "Indica si el cliente y el tercero pueden firmar juntos el contrato principal pese a vivir en regiones distintas.",
          dataType: "enum",
          enumValues: ["si", "no"],
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: [
            "Transferencias de inmuebles entre regiones distintas",
            "Compraventa de vehículo entre regiones distintas",
            "Compraventa de bienes muebles entre regiones distintas",
            "Compraventa tradicional de acciones entre regiones distintas",
          ],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y el equipo legal deben validar la persistencia de la respuesta. Solo se solicita en transferencias de inmuebles, compraventa de vehículo, compraventa de bienes muebles y compraventa tradicional de acciones cuando cliente y tercero viven en regiones distintas; se excluye Empresa en un Día.",
          },
        },
        tipoMandatoFirma: {
          id: "tipoMandatoFirma",
          productDescription:
            "Tipo de mandato que debe agregarse cuando las partes no pueden firmar juntas.",
          dataType: "enum",
          enumValues: ["autocontrato", "mandatoGeneral"],
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Creación de Mandato", "Creación de Mandato con autocontrato"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "El equipo legal y TI deben validar los nombres definitivos del catálogo y cuándo corresponde cada tipo de mandato.",
          },
        },
      },
      states: [
        {
          id: "transferenciaBloqueada",
          productDescription: "El tercero no puede recibir la transferencia.",
          activationCondition:
            "El tercero es cónyuge o, siendo mayor de 60 años, responde que no se encuentra en plenas facultades mentales.",
          visualImpact: "Muestra un aviso persistente y deshabilita Guardar y continuar.",
          usedIn: ["Evaluación de la transferencia"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "El equipo legal debe validar la redacción y alcance del bloqueo absoluto.",
          },
        },
        {
          id: "certificadoFacultadesMentalesRequerido",
          productDescription:
            "La transferencia requiere acreditar las facultades mentales del tercero.",
          activationCondition:
            "El tercero tiene más de 60 años, independientemente de la respuesta sobre sus facultades mentales.",
          visualImpact:
            "Muestra siempre la solicitud y agrega a Documentos un certificado emitido por psiquiatra o neurólogo.",
          usedIn: ["Evaluación de la transferencia", "Documentos de la gestión"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "El equipo legal debe validar el contenido exigido al certificado médico y el tratamiento del caso si no se acredita.",
          },
        },
        {
          id: "riesgoAceptableConConfirmacion",
          productDescription:
            "Existen señales de riesgo, pero el cliente puede continuar aceptándolas.",
          activationCondition:
            "Existe al menos una señal acumulativa y no hay impedimentos absolutos.",
          visualImpact:
            "Muestra las razones, recomienda escoger otra persona y exige una aceptación explícita.",
          usedIn: ["Evaluación de la transferencia"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "sensitive",
          technicalValidation: {
            status: "pendingTi",
            note: "El equipo legal debe validar cuándo una transferencia riesgosa puede continuar.",
          },
        },
      ],
    },
    conyugeTerceroAutorizante: {
      id: "conyugeTerceroAutorizante",
      productDescription:
        "Cónyuge o conviviente civil del tercero de confianza que debe comparecer a autorizar la transferencia de un inmueble.",
      roleInExperience:
        "Reúne los datos personales del compareciente y lo vincula con el tercero, la gestión y el cliente.",
      usedIn: ["Datos del tercero de confianza", "Comparecencia para autorización"],
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "sensitive",
      technicalValidation: {
        status: "pendingTi",
        note: "TI y el equipo legal deben validar la fuente, persistencia y vinculación del cónyuge o conviviente civil autorizante.",
      },
      fields: {
        nombres: crearCampoFormulario(
          "nombres",
          "Nombres del cónyuge o conviviente civil del tercero.",
          "string",
          ["Datos de quien comparece a autorizar"],
          "sensitive",
        ),
        apellidoPaterno: crearCampoFormulario(
          "apellidoPaterno",
          "Apellido paterno del cónyuge o conviviente civil del tercero.",
          "string",
          ["Datos de quien comparece a autorizar"],
          "sensitive",
        ),
        apellidoMaterno: crearCampoFormulario(
          "apellidoMaterno",
          "Apellido materno del cónyuge o conviviente civil del tercero.",
          "string",
          ["Datos de quien comparece a autorizar"],
          "sensitive",
        ),
        rut: crearCampoFormulario(
          "rut",
          "RUT del cónyuge o conviviente civil del tercero.",
          "string",
          ["Datos de quien comparece a autorizar"],
          "sensitive",
        ),
        email: crearCampoFormulario(
          "email",
          "Correo del cónyuge o conviviente civil del tercero.",
          "string",
          ["Datos de quien comparece a autorizar"],
          "sensitive",
        ),
        fechaNacimiento: crearCampoFormulario(
          "fechaNacimiento",
          "Fecha de nacimiento del cónyuge o conviviente civil del tercero.",
          "date",
          ["Datos de quien comparece a autorizar"],
          "sensitive",
        ),
        nacionalidad: crearCampoFormulario(
          "nacionalidad",
          "Nacionalidad del cónyuge o conviviente civil del tercero.",
          "string",
          ["Datos de quien comparece a autorizar"],
          "sensitive",
        ),
        profesion: crearCampoFormulario(
          "profesion",
          "Profesión u oficio del cónyuge o conviviente civil del tercero.",
          "string",
          ["Datos de quien comparece a autorizar"],
          "sensitive",
        ),
        estadoCivil: crearCampoFormulario(
          "estadoCivil",
          "Estado civil compartido con el tercero.",
          "string",
          ["Datos de quien comparece a autorizar"],
          "sensitive",
        ),
        regimenMatrimonial: crearCampoFormulario(
          "regimenMatrimonial",
          "Régimen patrimonial compartido con el tercero.",
          "string",
          ["Datos de quien comparece a autorizar"],
          "sensitive",
        ),
        domicilio: crearCampoFormulario(
          "domicilio",
          "Domicilio del cónyuge o conviviente civil del tercero.",
          "string",
          ["Datos de quien comparece a autorizar"],
          "sensitive",
        ),
        comuna: crearCampoFormulario(
          "comuna",
          "Comuna del domicilio del cónyuge o conviviente civil del tercero.",
          "string",
          ["Datos de quien comparece a autorizar"],
          "sensitive",
        ),
        region: crearCampoFormulario(
          "region",
          "Región del domicilio del cónyuge o conviviente civil del tercero.",
          "string",
          ["Datos de quien comparece a autorizar"],
          "sensitive",
        ),
      },
    },
    inmuebleHeredado: {
      id: "inmuebleHeredado",
      productDescription: "Inmueble incluido en una cesión de derechos hereditarios.",
      roleInExperience:
        "Permite identificar cada inmueble de la herencia, aplicar la regla del Conservador por comuna y solicitar documentos por bien.",
      usedIn: [
        "Datos del bien de Cesión de derechos hereditarios",
        "Regla del tercero por comuna",
        "Documentos por inmueble heredado",
      ],
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: {
        status: "pendingTi",
        note: "TI y Operaciones deben validar la estructura y persistencia definitiva de los inmuebles incluidos en una herencia.",
      },
      fields: {
        direccion: crearCampoFormulario("direccion", "Dirección del inmueble heredado.", "string", [
          "Datos del bien",
          "Identificador del inmueble",
          "Documentos por bien",
        ]),
        comuna: crearCampoFormulario(
          "comuna",
          "Comuna del inmueble heredado que determina la regla del Conservador.",
          "string",
          ["Datos del bien", "Regla del tercero por comuna"],
        ),
        region: crearCampoFormulario(
          "region",
          "Región administrativa del inmueble heredado.",
          "string",
          ["Datos del bien"],
        ),
      },
    },
    inmuebleMandato: {
      id: "inmuebleMandato",
      productDescription: "Inmueble que el cliente incluirá en un mandato.",
      roleInExperience:
        "Permite agregar y singularizar uno o más inmuebles dentro de una misma gestión de mandato.",
      usedIn: ["Bienes del mandato", "Mandato", "Mandato con autocontrato"],
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: {
        status: "pendingTi",
        note: "TI y Operaciones deben validar la persistencia de múltiples inmuebles y su estructura definitiva.",
      },
      fields: {
        direccion: crearCampoFormulario(
          "direccion",
          "Dirección del inmueble incluido en el mandato.",
          "string",
          ["Bienes del mandato"],
        ),
        comuna: crearCampoFormulario(
          "comuna",
          "Comuna del inmueble incluido en el mandato.",
          "string",
          ["Bienes del mandato"],
        ),
        region: crearCampoFormulario(
          "region",
          "Región del inmueble incluido en el mandato.",
          "string",
          ["Bienes del mandato"],
        ),
      },
    },
    bienMueble: {
      id: "bienMueble",
      productDescription:
        "Tipo de bien mueble individualizado dentro de una compraventa, comodato o mandato.",
      roleInExperience:
        "Permite ingresar, revisar y editar listas extensas de bienes muebles, agrupando los bienes iguales mediante su cantidad.",
      usedIn: [
        "Compraventa de bienes muebles",
        "Comodato de bienes muebles",
        "Mandatos que incluyen bienes muebles",
      ],
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: {
        status: "pendingTi",
        note: "TI y Operaciones deben validar la estructura y persistencia definitiva de la colección de bienes muebles.",
      },
      fields: {
        idBienMueble: {
          id: "idBienMueble",
          productDescription:
            "Identificador técnico estable de la fila para editar, duplicar o eliminar el bien sin confundirlo con otro.",
          dataType: "identifier",
          derivation:
            "Se genera al crear o normalizar una fila y se conserva aunque cambie su posición en la lista.",
          required: true,
          usage: {
            visible: false,
            editable: false,
            calculated: true,
            technical: true,
          },
          usedIn: ["Edición de la tabla de bienes muebles"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe definir si el identificador se conserva en backend o solo durante la edición del formulario.",
          },
        },
        tipoBien: crearCampoFormulario(
          "tipoBien",
          "Descripción cotidiana del tipo de bien mueble.",
          "string",
          ["Tabla de bienes muebles", "Individualización del bien"],
        ),
        cantidad: crearCampoFormulario(
          "cantidad",
          "Cantidad de bienes iguales agrupados en la misma fila.",
          "number",
          ["Tabla de bienes muebles", "Individualización del bien"],
        ),
        marca: crearCampoFormulario("marca", "Marca del bien mueble.", "string", [
          "Tabla de bienes muebles",
          "Individualización del bien",
        ]),
        color: crearCampoFormulario("color", "Color del bien mueble.", "string", [
          "Tabla de bienes muebles",
          "Individualización del bien",
        ]),
      },
    },
    vehiculoTransferencia: {
      id: "vehiculoTransferencia",
      productDescription:
        "Vehículo que el cliente transferirá mediante compraventa o directamente en el Registro Civil.",
      roleInExperience:
        "Permite identificar el vehículo y detener la transferencia mientras exista una prenda vigente.",
      usedIn: ["Compraventa de vehículo", "Transferencia de vehículo RC", "Datos del bien"],
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: {
        status: "pendingTi",
        note: "TI y Operaciones deben validar la fuente, persistencia y actualización de la situación registral de la prenda.",
      },
      fields: {
        patente: crearCampoFormulario(
          "patente",
          "Placa patente del vehículo que se transferirá.",
          "string",
          ["Datos del bien", "Cards del portal de gestiones"],
        ),
        permisoAlDia: {
          id: "permisoAlDia",
          productDescription: "Indica si el permiso de circulación del vehículo está al día.",
          dataType: "enum",
          enumValues: ["si", "no"],
          required: true,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Datos del bien", "Compraventa de vehículo", "Transferencia de vehículo RC"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben validar la fuente y persistencia del estado del permiso de circulación.",
          },
        },
        prenda: {
          id: "prenda",
          productDescription: "Indica si el vehículo tiene una prenda vigente.",
          dataType: "enum",
          enumValues: ["si", "no"],
          required: true,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Datos del bien", "Control previo de la transferencia del vehículo"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben validar si la respuesta del cliente se contrastará con información registral.",
          },
        },
        deudaPrendaAlDia: {
          id: "deudaPrendaAlDia",
          productDescription:
            "Indica si los pagos de la deuda asociada a la prenda vigente están al día.",
          dataType: "enum",
          enumValues: ["si", "no"],
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: [
            "Evaluación condicional de la prenda",
            "Compraventa de vehículo",
            "Transferencia de vehículo RC",
          ],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben validar la fuente y persistencia del estado de pago de la deuda prendaria.",
          },
        },
        cuotasPendientesPrenda: {
          id: "cuotasPendientesPrenda",
          productDescription:
            "Cantidad de cuotas pendientes cuando la deuda asociada a la prenda está al día.",
          dataType: "enum",
          enumValues: ["1", "2", "3", "masDe3", "deudaPagada"],
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Evaluación condicional de la prenda", "Estado en espera del alzamiento"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben validar el catálogo y la persistencia de las cuotas pendientes.",
          },
        },
      },
      states: [
        {
          id: "transferenciaRegistroCivilBloqueadaPorPermiso",
          productDescription:
            "La transferencia directa ante el Registro Civil no puede continuar mientras el permiso de circulación no esté al día.",
          activationCondition:
            "El contrato es Transferencia de vehículo RC y permisoAlDia tiene el valor no.",
          visualImpact:
            "Muestra un impedimento junto a los datos del vehículo. Permite guardar el estado sin avanzar y volver al portal, donde la gestión aparece como No puede continuar. Esta regla no se aplica a Compraventa de vehículo.",
          usedIn: ["Transferencia de vehículo RC", "Datos del bien"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben validar la persistencia y evaluación del permiso de circulación según el tipo de transferencia.",
          },
        },
        {
          id: "esperandoAlzamientoPrenda",
          productDescription:
            "La gestión queda guardada, pero no puede avanzar mientras la prenda siga vigente.",
          activationCondition: "La deuda está al día y quedan entre una y tres cuotas pendientes.",
          visualImpact:
            "Muestra una orientación calmada, vuelve al portal y presenta el estado En espera del alzamiento con una acción para actualizar los datos.",
          usedIn: [
            "Compraventa de vehículo",
            "Transferencia de vehículo RC",
            "Portal de gestiones",
          ],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben validar la persistencia y transición del estado de espera.",
          },
        },
        {
          id: "transferenciaBloqueadaPorPrenda",
          productDescription:
            "La transferencia no puede continuar porque la deuda tiene pagos atrasados, faltan más de tres cuotas o la prenda sigue vigente después del pago total.",
          activationCondition:
            "Existe una prenda vigente y la deuda no está al día, quedan más de tres cuotas pendientes o la deuda está pagada pero el alzamiento aún no se ha realizado.",
          visualImpact:
            "Explica todas las causas aplicables por las que no se puede avanzar y permite guardar el estado sin continuar. En el portal, la gestión aparece como No puede continuar y ofrece actualizar los antecedentes. Si la deuda ya está pagada, no pregunta por el estado de cuotas pendientes y exige el alzamiento de la prenda.",
          usedIn: ["Compraventa de vehículo", "Transferencia de vehículo RC"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben validar las reglas definitivas que impiden iniciar o continuar la transferencia.",
          },
        },
      ],
    },
    documento: {
      id: "documento",
      productDescription:
        "Documento requerido para completar una gestión y revisado posteriormente por el equipo legal.",
      roleInExperience:
        "Orienta a la persona para obtener cada antecedente, permite cargarlo y muestra el resultado de su revisión.",
      usedIn: ["Documentos de la gestión", "Revisión legal de documentos"],
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "sensitive",
      technicalValidation: {
        status: "pendingTi",
        note: "TI debe confirmar el almacenamiento seguro de archivos, sus URLs de visualización y la integración con la revisión legal.",
      },
      fields: {
        nombre: crearCampoFormulario(
          "nombre",
          "Nombre del documento solicitado para la gestión; cuando corresponde a varios bienes, incluye la dirección del inmueble o la placa patente del vehículo.",
          "string",
          ["Documentos de la gestión"],
          "internal",
        ),
        instruccionesObtencion: crearCampoFormulario(
          "instruccionesObtencion",
          "Indicación breve y visible que explica cómo obtener el documento dentro de Lexy.",
          "string",
          ["Documentos de la gestión"],
          "internal",
        ),
        estadoRevision: {
          id: "estadoRevision",
          productDescription: "Resultado de la revisión del archivo cargado por el equipo legal.",
          dataType: "enum",
          enumValues: ["pendiente", "aprobado", "rechazado"],
          required: false,
          usage: {
            visible: true,
            editable: false,
            calculated: false,
            technical: false,
          },
          usedIn: ["Documentos de la gestión", "Revisión legal de documentos"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben confirmar los estados, las transiciones y quién puede aprobar o rechazar un documento.",
          },
        },
        nombreArchivo: crearCampoFormulario(
          "nombreArchivo",
          "Nombre del archivo que la persona cargó para cumplir el requisito.",
          "string",
          ["Documentos de la gestión"],
          "internal",
          false,
        ),
        urlArchivo: crearCampoFormulario(
          "urlArchivo",
          "URL segura usada para abrir el documento cargado en una nueva pestaña.",
          "string",
          ["Documentos de la gestión"],
          "restricted",
          false,
        ),
        motivoRechazo: crearCampoFormulario(
          "motivoRechazo",
          "Explicación visible para que la persona corrija y vuelva a cargar un documento rechazado.",
          "string",
          ["Documentos de la gestión"],
          "internal",
          false,
        ),
      },
      states: [
        {
          id: "pendiente",
          productDescription: "El archivo fue cargado y espera la revisión del equipo legal.",
          activationCondition: "La persona carga un archivo o reemplaza una versión rechazada.",
          visualImpact:
            "Muestra Pendiente de aprobación junto al nombre del archivo y permite visualizarlo, sin reemplazarlo mientras está en revisión.",
          usedIn: ["Documentos de la gestión"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe confirmar el evento que deja el documento pendiente de revisión.",
          },
        },
        {
          id: "aprobado",
          productDescription: "El equipo legal aprobó el documento cargado.",
          activationCondition: "Una persona autorizada aprueba el documento tras revisarlo.",
          visualImpact: "Muestra Aprobado junto al archivo y permite visualizarlo.",
          usedIn: ["Documentos de la gestión"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe confirmar cómo se publica la aprobación en la ficha del cliente.",
          },
        },
        {
          id: "rechazado",
          productDescription: "El equipo legal rechazó el documento e informó cómo corregirlo.",
          activationCondition: "Una persona autorizada rechaza el documento e ingresa un motivo.",
          visualImpact: "Muestra Rechazado, el motivo y habilita la carga de una nueva versión.",
          usedIn: ["Documentos de la gestión"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe confirmar la persistencia y visibilidad del motivo de rechazo.",
          },
        },
      ],
    },
    gestion: {
      id: "gestion",
      productDescription: "Gestión o escritura que el cliente completa en el portal.",
      roleInExperience: "Define el nombre de la escritura y la secuencia de pasos del flujo.",
      usedIn: ["Portal de gestiones", "Flujo de antecedentes", "Simulador"],
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: {
        status: "pendingTi",
        note: "TI debe confirmar la fuente y los identificadores definitivos del catálogo de escrituras.",
      },
      fields: {
        tipoContrato: {
          id: "tipoContrato",
          productDescription: "Nombre del contrato o escritura asociado a la gestión.",
          dataType: "enum",
          enumValues: [
            "Compraventa de Inmueble",
            "Cancelación y Alzamiento de Hipoteca",
            "Compraventa de Inmueble y usufructo",
            "Cesión de derechos",
            "Compraventa de nuda propiedad",
            "Cesión de derechos hereditarios",
            "Compraventa de bienes muebles",
            "Comodato de bienes muebles",
            "Declaración jurada de Allegado",
            "Mandato",
            "Mandato con autocontrato",
            "Resciliación",
            "Pacto de sustitución de régimen matrimonial",
            "Liquidación de sociedad conyugal",
            "Renuncia a los gananciales",
            "Compraventa de vehículo",
            "Cancelación y Alzamiento de Prenda",
            "Transferencia de vehículo RC",
            "Compraventa de acciones (Régimen tradicional)",
            "Compraventa de acciones (Empresa en un Día)",
            "Constitución de sociedades",
            "Compraventa de establecimiento comercial",
            "Compraventa de patente comercial",
            "Contrato de arriendo",
            "Aporte inmobiliario SRL",
          ],
          derivation:
            "En inmuebles se evalúan tipoAdquisicion y tipoTitularidadInmueble para resolver una cesión de derechos. En Liquidación de sociedad conyugal, si comproInmueble y comproVehiculo son 'no', cambia a Pacto de sustitución de régimen matrimonial con separación de bienes como régimen de destino fijo; si alguna respuesta cambia a 'sí', restaura tipoContratoOriginal.",
          required: true,
          usage: {
            visible: true,
            editable: false,
            calculated: true,
            technical: false,
          },
          usedIn: [
            "Portal de gestiones",
            "Flujo de antecedentes",
            "Simulador",
            "Tipo de adquisición",
          ],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe validar los nombres e identificadores del catálogo de escrituras.",
          },
        },
        estadoGestion: {
          id: "estadoGestion",
          productDescription:
            "Estado actual de la gestión que determina su avance y la acción disponible en el portal.",
          dataType: "enum",
          enumValues: [
            "pendiente_datos",
            "esperando_alzamiento",
            "transferencia_bloqueada",
            "faltan_documentos",
            "en_revision",
            "completado",
          ],
          derivation:
            "En transferencias de vehículos, esperando_alzamiento se usa únicamente cuando quedan entre una y tres cuotas al día. transferencia_bloqueada se usa cuando el permiso exigido no está al día, existen cuotas atrasadas, quedan más de tres cuotas o falta alzar una prenda cuya deuda ya fue pagada.",
          required: true,
          usage: {
            visible: true,
            editable: false,
            calculated: true,
            technical: false,
          },
          usedIn: ["Portal de gestiones", "Flujo de antecedentes", "Simulador"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben validar la persistencia y las transiciones de los estados de espera y bloqueo de transferencias.",
          },
        },
        fichaEnviada: {
          id: "fichaEnviada",
          productDescription:
            "Indica que la persona envió los datos de la ficha y que desde ese momento solo puede revisarlos.",
          dataType: "boolean",
          required: true,
          usage: {
            visible: true,
            editable: false,
            calculated: false,
            technical: false,
          },
          usedIn: ["Bloqueo de edición de la ficha", "Revisión de respuestas enviadas"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe confirmar la persistencia definitiva del envío de la ficha y que solo el equipo autorizado pueda habilitar una corrección posterior.",
          },
        },
        identificadorPortal: {
          id: "identificadorPortal",
          productDescription:
            "Texto breve que distingue la gestión en la card del portal a partir del bien o sociedad informado.",
          dataType: "string",
          derivation:
            "Muestra direccion en contratos de inmueble, arriendo y aporte inmobiliario; patente en contratos de vehículo; razonSocial en compraventas de acciones; nombreSociedad en constitución de sociedades. En cesión de derechos hereditarios muestra la única dirección o, si existen varias, la cantidad con el formato '(N inmuebles)'. Los demás contratos no muestran identificador.",
          required: false,
          usage: {
            visible: true,
            editable: false,
            calculated: true,
            technical: false,
          },
          usedIn: ["Cards del portal de gestiones"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe validar que los campos de origen estén disponibles al cargar las gestiones del portal.",
          },
        },
        tipoAdquisicion: {
          id: "tipoAdquisicion",
          productDescription: "Forma en que el cliente adquirió el inmueble asociado a la gestión.",
          dataType: "enum",
          enumValues: [
            "sin-credito",
            "con-credito",
            "subsidio",
            "subsidio-hipotecario",
            "herencia-inscrita",
            "herencia-no-inscrita",
          ],
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Datos del bien", "Mutación a cesión de derechos hereditarios"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe confirmar el catálogo de tipos de adquisición y la regla que transforma el contrato cuando el inmueble proviene de una herencia.",
          },
        },
        cantidadHerederos: {
          id: "cantidadHerederos",
          productDescription:
            "Cantidad total de personas herederas informada para la cesión de derechos hereditarios.",
          dataType: "number",
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Datos del bien de Cesión de derechos hereditarios"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben confirmar la fuente, validación y persistencia de la cantidad de personas herederas.",
          },
        },
        tipoTitularidadInmueble: {
          id: "tipoTitularidadInmueble",
          productDescription:
            "Indica si el cliente es la única persona propietaria del inmueble o si comparte la propiedad.",
          dataType: "enum",
          enumValues: ["propiedadExclusiva", "copropiedad"],
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Datos del bien", "Mutación a cesión de derechos"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben validar que la copropiedad transforma la compraventa de inmueble en una cesión de derechos.",
          },
        },
        formaConstitucionSociedadPatente: {
          id: "formaConstitucionSociedadPatente",
          productDescription:
            "Forma en que fue constituida la sociedad titular de la patente comercial que se transferirá.",
          dataType: "enum",
          enumValues: ["escrituraPublica", "empresaEnUnDia"],
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Datos del bien de Compraventa de patente comercial"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y el equipo legal deben validar la fuente, persistencia y catálogo definitivo de la forma de constitución de la sociedad titular de la patente comercial.",
          },
        },
        mandatoInmuebles: crearCampoFormulario(
          "mandatoInmuebles",
          "Indica si el mandato incluirá uno o más inmuebles.",
          "boolean",
          ["Selección de bienes del mandato"],
          "internal",
          false,
        ),
        mandatoVehiculos: crearCampoFormulario(
          "mandatoVehiculos",
          "Indica si el mandato incluirá un vehículo.",
          "boolean",
          ["Selección de bienes del mandato"],
          "internal",
          false,
        ),
        mandatoMuebles: crearCampoFormulario(
          "mandatoMuebles",
          "Indica si el mandato incluirá bienes muebles.",
          "boolean",
          ["Selección de bienes del mandato"],
          "internal",
          false,
        ),
        mandatoAcciones: crearCampoFormulario(
          "mandatoAcciones",
          "Indica si el mandato incluirá acciones de una sociedad.",
          "boolean",
          ["Selección de bienes del mandato"],
          "internal",
          false,
        ),
        razonSocial: crearCampoFormulario(
          "razonSocial",
          "Razón social de la empresa cuyas participaciones o acciones se transferirán.",
          "string",
          [
            "Compraventa de acciones (Régimen tradicional)",
            "Compraventa de acciones (Empresa en un Día)",
            "Bien vinculado en mandato",
          ],
          "internal",
        ),
        rutEmpresa: crearCampoFormulario(
          "rutEmpresa",
          "RUT de la empresa cuyas participaciones o acciones se transferirán.",
          "string",
          [
            "Compraventa de acciones (Régimen tradicional)",
            "Compraventa de acciones (Empresa en un Día)",
            "Bien vinculado en mandato",
          ],
          "internal",
        ),
        tipoSocietarioAcciones: {
          id: "tipoSocietarioAcciones",
          productDescription:
            "Tipo societario de la empresa cuyas participaciones o acciones se transferirán.",
          dataType: "enum",
          enumValues: ["srl", "spa", "sa"],
          required: true,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: [
            "Compraventa de acciones (Régimen tradicional)",
            "Compraventa de acciones (Empresa en un Día)",
            "Bien vinculado en mandato",
          ],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben validar el catálogo y la persistencia del tipo societario para compraventas de acciones.",
          },
        },
        participacion: {
          id: "participacion",
          productDescription:
            "Porcentaje de participación que se transferirá cuando la empresa sea una sociedad de responsabilidad limitada.",
          dataType: "number",
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: ["Compraventa de acciones de SRL", "Bien vinculado en mandato"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben validar la persistencia del porcentaje y su rango entre 1 y 100.",
          },
        },
        numeroAcciones: {
          id: "numeroAcciones",
          productDescription:
            "Cantidad de acciones que se transferirá cuando la empresa sea una SpA o S.A.",
          dataType: "number",
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: [
            "Compraventa de acciones de SpA",
            "Compraventa de acciones de S.A.",
            "Bien vinculado en mandato",
          ],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben validar la persistencia de la cantidad de acciones transferidas.",
          },
        },
        gestionOrigenId: {
          id: "gestionOrigenId",
          productDescription:
            "Identificador de la gestión principal cuyos bienes comparte el mandato creado para resolver la firma.",
          dataType: "identifier",
          derivation:
            "Se asigna al mandato cuando se crea desde una gestión principal por falta de firma conjunta.",
          required: false,
          usage: {
            visible: false,
            editable: false,
            calculated: true,
            technical: true,
          },
          usedIn: ["Prerrelleno y sincronización del bien en el mandato"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe definir el identificador persistente que vinculará el mandato con su contrato principal.",
          },
        },
        nombreContratoOrigen: {
          id: "nombreContratoOrigen",
          productDescription:
            "Nombre del contrato principal usado para mantener las reglas de edición del bien vinculado.",
          dataType: "string",
          derivation: "Se copia desde tipoContrato al crear o actualizar el mandato vinculado.",
          required: false,
          usage: {
            visible: false,
            editable: false,
            calculated: true,
            technical: true,
          },
          usedIn: ["Edición del bien vinculado en el mandato"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe confirmar si este dato se persiste o se resuelve mediante la relación con la gestión principal.",
          },
        },
        gestionMandatoFirmaId: {
          id: "gestionMandatoFirmaId",
          productDescription:
            "Identificador del mandato creado para resolver la firma de la gestión principal.",
          dataType: "identifier",
          derivation:
            "Se asigna a la gestión principal al crear su mandato y se elimina si las partes vuelven a declarar que pueden firmar juntas.",
          required: false,
          usage: {
            visible: false,
            editable: false,
            calculated: true,
            technical: true,
          },
          usedIn: ["Sincronización bidireccional del bien entre contratos"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe definir el identificador persistente del mandato asociado a cada contrato principal.",
          },
        },
        comproInmueble: {
          id: "comproInmueble",
          productDescription:
            "Indica si el cliente adquirió inmuebles durante el matrimonio que deban considerarse en la liquidación.",
          dataType: "enum",
          enumValues: ["si", "no"],
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: [
            "Datos del bien de Liquidación de sociedad conyugal",
            "Cambio a Pacto de sustitución de régimen matrimonial",
          ],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben validar la persistencia de la respuesta y su uso para cambiar el tipo de contrato.",
          },
        },
        comproVehiculo: {
          id: "comproVehiculo",
          productDescription:
            "Indica si el cliente adquirió vehículos durante el matrimonio que deban considerarse en la liquidación.",
          dataType: "enum",
          enumValues: ["si", "no"],
          required: false,
          usage: {
            visible: true,
            editable: true,
            calculated: false,
            technical: false,
          },
          usedIn: [
            "Datos del bien de Liquidación de sociedad conyugal",
            "Cambio a Pacto de sustitución de régimen matrimonial",
          ],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben validar la persistencia de la respuesta y su uso para cambiar el tipo de contrato.",
          },
        },
        regimenMatrimonialDestino: {
          id: "regimenMatrimonialDestino",
          productDescription:
            "Régimen patrimonial al que pasarán la persona y su cónyuge mediante el pacto de sustitución.",
          dataType: "enum",
          enumValues: ["separacionDeBienes"],
          derivation:
            "Se fija automáticamente en separacionDeBienes cuando una Liquidación de sociedad conyugal cambia a Pacto de sustitución de régimen matrimonial porque no hay inmuebles ni vehículos adquiridos durante el matrimonio.",
          required: false,
          usage: {
            visible: true,
            editable: false,
            calculated: true,
            technical: false,
          },
          usedIn: [
            "Card informativa del cambio a Pacto de sustitución de régimen matrimonial",
            "Preparación del pacto con separación de bienes",
          ],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben confirmar que todo pacto originado por ausencia de bienes usa separación de bienes como régimen de destino y definir su persistencia.",
          },
        },
        tipoContratoOriginal: {
          id: "tipoContratoOriginal",
          productDescription:
            "Tipo de contrato con el que nació la gestión, conservado para restaurarlo si cambia una respuesta que determina el contrato aplicable.",
          dataType: "string",
          derivation:
            "Se copia desde tipoContrato antes de la primera mutación automática por adquisición, titularidad o existencia de bienes en una liquidación.",
          required: false,
          usage: {
            visible: false,
            editable: false,
            calculated: true,
            technical: true,
          },
          usedIn: ["Restauración del contrato original"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe confirmar si el tipo original vendrá informado por backend o se conservará solo durante la sesión del formulario.",
          },
        },
        requiereDatosBien: {
          id: "requiereDatosBien",
          productDescription: "Indica si el flujo debe solicitar antecedentes del bien.",
          dataType: "boolean",
          required: true,
          usage: {
            visible: false,
            editable: false,
            calculated: false,
            technical: true,
          },
          usedIn: ["Secuencia del flujo de antecedentes"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI debe confirmar qué escrituras requieren datos de un bien.",
          },
        },
        modoPersonaRelacionada: {
          id: "modoPersonaRelacionada",
          productDescription:
            "Define si se solicitan datos de una persona relacionada o si el paso se reemplaza por instrucciones para transferir un vehículo en el Registro Civil.",
          dataType: "enum",
          enumValues: [
            "soloTercero",
            "soloConyuge",
            "terceroConConyugeCondicional",
            "segundoSocio",
            "registroCivilVehiculo",
          ],
          required: true,
          usage: {
            visible: false,
            editable: false,
            calculated: false,
            technical: true,
          },
          usedIn: ["Secuencia del flujo de antecedentes"],
          origin: "generatedByUsability",
          source: { kind: "unknown" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "TI y Operaciones deben validar las reglas de comparecientes por escritura y que Transferencia de vehículo RC reemplace la captura del tercero por orientación presencial.",
          },
        },
        requiereDocumentos: {
          id: "requiereDocumentos",
          productDescription: "Indica si la gestión termina con una solicitud de documentos.",
          dataType: "boolean",
          derivation:
            "Es falso para Constitución de sociedades, Compraventa de bienes muebles y Comodato de bienes muebles, que finalizan al guardar sus datos. Transferencia de vehículo RC solicita exclusivamente el comprobante de solicitud de transferencia emitido por el Registro Civil; para los demás contratos se mantiene la solicitud documental definida por la gestión.",
          required: true,
          usage: {
            visible: false,
            editable: false,
            calculated: true,
            technical: true,
          },
          usedIn: ["Secuencia del flujo de antecedentes"],
          origin: "generatedByUsability",
          source: { kind: "derived" },
          dataClassification: "internal",
          technicalValidation: {
            status: "pendingTi",
            note: "Constitución de sociedades, Compraventa de bienes muebles y Comodato de bienes muebles no solicitan documentos. Transferencia de vehículo RC solicita solo el comprobante del Registro Civil. La lista documental de los demás contratos queda pendiente de definición con Operaciones y TI.",
          },
        },
      },
    },
  },
  relations: [
    {
      id: "gestionDocumentos",
      fromEntity: "gestion",
      toEntity: "documento",
      cardinality: "oneToMany",
      productDescription:
        "Vincula una gestión con los documentos que la persona debe obtener, cargar y enviar a revisión; los requisitos se derivan del tipo de escritura y de los bienes declarados.",
      requiredBy: ["Documentos de la gestión", "Revisión legal de documentos"],
      resolution: "queried",
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "sensitive",
      technicalValidation: {
        status: "pendingTi",
        note: "TI debe confirmar el identificador de la gestión, la lista definitiva de documentos por escritura, su repetición por cada bien y su persistencia.",
      },
    },
    {
      id: "gestionMandatoFirma",
      fromEntity: "gestion",
      toEntity: "gestion",
      cardinality: "oneToOne",
      productDescription:
        "Vincula el contrato principal con el mandato creado cuando cliente y tercero no pueden firmar juntos, compartiendo también sus requisitos y estados documentales.",
      requiredBy: [
        "Transferencias de inmuebles entre regiones distintas sin firma conjunta",
        "Compraventa de vehículo entre regiones distintas sin firma conjunta",
        "Compraventa de bienes muebles entre regiones distintas sin firma conjunta",
        "Compraventa tradicional de acciones entre regiones distintas sin firma conjunta",
      ],
      resolution: "embedded",
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: {
        status: "pendingTi",
        note: "TI debe validar la relación uno a uno y el mecanismo definitivo de sincronización bidireccional del bien y de los documentos compartidos.",
      },
    },
    {
      id: "gestionOtorganteMandato",
      fromEntity: "gestion",
      toEntity: "otorganteMandato",
      cardinality: "oneToOne",
      productDescription:
        "Vincula el mandato simple con el tercero que otorga el poder cuando no es el cliente.",
      requiredBy: [
        "Mandato cuando el tercero otorga el poder y sus datos no están disponibles desde el contrato principal",
      ],
      resolution: "embedded",
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "sensitive",
      technicalValidation: {
        status: "pendingTi",
        note: "TI debe validar la reutilización del tercero del contrato principal y la persistencia del otorgante.",
      },
    },
    {
      id: "gestionInmueblesHeredados",
      fromEntity: "gestion",
      toEntity: "inmuebleHeredado",
      cardinality: "oneToMany",
      productDescription:
        "Vincula una cesión de derechos hereditarios con cada inmueble declarado en la herencia.",
      requiredBy: [
        "Datos del bien de Cesión de derechos hereditarios",
        "Regla del tercero por comuna",
        "Documentos por inmueble heredado",
      ],
      resolution: "embedded",
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: {
        status: "pendingTi",
        note: "TI debe definir la relación persistente entre la gestión y sus inmuebles heredados.",
      },
    },
    {
      id: "gestionInmueblesMandato",
      fromEntity: "gestion",
      toEntity: "inmuebleMandato",
      cardinality: "oneToMany",
      productDescription:
        "Vincula una gestión de mandato con todos los inmuebles incluidos por el cliente.",
      requiredBy: ["Mandato y Mandato con autocontrato cuando se seleccionan inmuebles"],
      resolution: "embedded",
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: {
        status: "pendingTi",
        note: "TI debe validar la estructura de la colección de inmuebles y su persistencia en la gestión.",
      },
    },
    {
      id: "gestionBienesMuebles",
      fromEntity: "gestion",
      toEntity: "bienMueble",
      cardinality: "oneToMany",
      productDescription:
        "Vincula una gestión con todos los tipos de bienes muebles individualizados por la persona.",
      requiredBy: [
        "Compraventa de bienes muebles",
        "Comodato de bienes muebles",
        "Mandato y Mandato con autocontrato cuando se seleccionan bienes muebles",
      ],
      resolution: "embedded",
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: {
        status: "pendingTi",
        note: "TI debe validar la relación uno a muchos y la persistencia del orden de las filas.",
      },
    },
    {
      id: "gestionSociedad",
      fromEntity: "gestion",
      toEntity: "sociedad",
      cardinality: "oneToOne",
      productDescription:
        "Vincula la gestión de constitución con los datos de la sociedad que se creará.",
      requiredBy: ["Constitución de sociedades"],
      resolution: "embedded",
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: {
        status: "pendingTi",
        note: "TI debe validar cómo se relacionará la gestión con la sociedad.",
      },
    },
    {
      id: "gestionSegundoSocio",
      fromEntity: "gestion",
      toEntity: "segundoSocio",
      cardinality: "oneToOne",
      productDescription:
        "Vincula la gestión de constitución con la persona que participa como segundo socio.",
      requiredBy: ["Constitución de sociedades"],
      resolution: "embedded",
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "sensitive",
      technicalValidation: {
        status: "pendingTi",
        note: "TI debe validar cómo se relacionará la gestión con el segundo socio.",
      },
    },
    {
      id: "gestionAdministradorSociedad",
      fromEntity: "gestion",
      toEntity: "administradorSociedadPersona",
      cardinality: "oneToOne",
      productDescription:
        "Vincula opcionalmente la gestión con la persona externa que administrará o representará a la sociedad.",
      requiredBy: ["Constitución de sociedades cuando administradorSociedad es otro"],
      resolution: "embedded",
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "sensitive",
      technicalValidation: {
        status: "pendingTi",
        note: "TI debe validar cómo se relacionará la gestión con el administrador o representante externo.",
      },
    },
    {
      id: "gestionConyugeTerceroAutorizante",
      fromEntity: "gestion",
      toEntity: "conyugeTerceroAutorizante",
      cardinality: "oneToOne",
      productDescription:
        "Vincula la transferencia de inmueble con el cónyuge o conviviente civil del tercero que comparece a autorizar.",
      requiredBy: [
        "Transferencias de inmuebles cuando el tercero está casado en sociedad conyugal o tiene AUC con comunidad de bienes",
      ],
      resolution: "embedded",
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "sensitive",
      technicalValidation: {
        status: "pendingTi",
        note: "TI debe validar la vinculación del compareciente autorizante con la gestión.",
      },
    },
    {
      id: "clienteConyugeTerceroAutorizante",
      fromEntity: "cliente",
      toEntity: "conyugeTerceroAutorizante",
      cardinality: "oneToMany",
      productDescription:
        "Vincula al cliente con los cónyuges o convivientes civiles de terceros que deban autorizar sus gestiones.",
      requiredBy: ["Comparecencia para autorizar transferencias de inmuebles del cliente"],
      resolution: "queried",
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "sensitive",
      technicalValidation: {
        status: "pendingTi",
        note: "TI debe validar el identificador que vinculará al cliente con cada compareciente autorizante.",
      },
    },
  ],
  projections: {},
});
